### ISSUE TITLE
Composer v2 support

### ISSUE THREAD

**Issue by Rarst** [lichunqiang/composer-ignore-plugin#2]
Hello,

Do you plan to update the plugin to allow Composer's v2 API?

I took a look if that's an easy change I could PR, but no experience with writing Composer plugins and upgrade list is quite long to quickly understand what's relevant https://getcomposer.org/upgrade/UPGRADE-2.0.md

Thank you either way, been using it for a while. :)

**Comment by lichunqiang** [comment]
2.0 is supported.

@Rarst have fun
